export const GET_DONUTS_REQUEST = "GET_DONUTS_REQUEST";
export const GET_DONUTS_SUCCESS = "GET_DONUTS_SUCCESS";
export const GET_DONUTS_FAIL = "GET_DONUTS_FAIL";

export const GET_DONUT_DETAILS_REQUEST = "GET_DONUT_DETAILS_REQUEST";
export const GET_DONUT_DETAILS_SUCCESS = "GET_DONUT_DETAILS_SUCCESS";
export const GET_DONUT_DETAILS_FAIL = "GET_DONUT_DETAILS_FAIL";
export const GET_DONUT_DETAILS_RESET = "GET_DONUT_DETAILS_RESET";