export const ORDER_CREATED = "ORDER_CREATED";
export const REVIEW_CREATED = "REVIEW_CREATED";
export const REVIEW_DELETED = "REVIEW_DELETED";
export const NOT_LOGGED_IN = "NOT_LOGGED_IN";

export const ORDER_CREATED_RESET = "ORDER_CREATED_RESET";
export const REVIEW_CREATED_RESET = "REVIEW_CREATED_RESET";
export const REVIEW_DELETED_RESET = "REVIEW_DELETED_RESET";
export const NOT_LOGGED_IN_RESET = "NOT_LOGGED_IN_RESET";