export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_REQUEST_SUCCESS = "POST_ORDER_REQUEST_SUCCESS";;
export const POST_ORDER_REQUEST_FAIL = "POST_ORDER_REQUEST_FAIL";
export const POST_ORDER_REQUEST_RESET = "POST_ORDER_REQUEST";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";  
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const GET_ORDERS_RESET = "GET_ORDERS_RESET";