export const POST_REVIEW_REQUEST = "POST_REVIEW_REQUEST";
export const POST_REVIEW_REQUEST_SUCCESS = "POST_REVIEW_REQUEST_SUCCESS";;
export const POST_REVIEW_REQUEST_FAIL = "POST_REVIEW_REQUEST_FAIL";
export const POST_REVIEW_REQUEST_RESET = "POST_REVIEW_REQUEST_RESET";

export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_REQUEST_SUCCESS = "GET_REVIEWS_REQUEST_SUCCESS";;
export const GET_REVIEWS_REQUEST_FAIL = "GET_REVIEWS_REQUEST_FAIL";
export const GET_REVIEWS_REQUEST_RESET = "GET_REVIEWS_REQUEST_RESET";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_REQUEST_SUCCESS = "DELETE_REVIEW_REQUEST_SUCCESS";;
export const DELETE_REVIEW_REQUEST_FAIL = "DELETE_REVIEW_REQUEST_FAIL";
export const DELETE_REVIEW_REQUEST_RESET = "DELETE_REVIEW_REQUEST_RESET";